/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LendingWithUsRouteImport } from './routes/lending-with-us'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomerServiceRouteImport } from './routes/customer-service'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OccasionsIndexRouteImport } from './routes/occasions.index'
import { Route as DesignersIndexRouteImport } from './routes/designers.index'
import { Route as OccasionsSlugRouteImport } from './routes/occasions.$slug'
import { Route as LendersLenderIdRouteImport } from './routes/lenders.$lenderId'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as LegalRefundsRouteImport } from './routes/legal/refunds'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalLenderRouteImport } from './routes/legal/lender'
import { Route as LegalDeliveryRouteImport } from './routes/legal/delivery'
import { Route as EditsSlugRouteImport } from './routes/edits.$slug'
import { Route as DressesIdRouteImport } from './routes/dresses.$id'
import { Route as DesignersSlugRouteImport } from './routes/designers.$slug'
import { Route as CitiesSlugRouteImport } from './routes/cities.$slug'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedCheckoutIndexRouteImport } from './routes/_authenticated/checkout/index'
import { Route as AuthenticatedDashboardVacationRouteImport } from './routes/_authenticated/dashboard/vacation'
import { Route as AuthenticatedDashboardTwoHourDeliveryRouteImport } from './routes/_authenticated/dashboard/two-hour-delivery'
import { Route as AuthenticatedDashboardTryOnRouteImport } from './routes/_authenticated/dashboard/try-on'
import { Route as AuthenticatedDashboardShippingRouteImport } from './routes/_authenticated/dashboard/shipping'
import { Route as AuthenticatedDashboardSavedRouteImport } from './routes/_authenticated/dashboard/saved'
import { Route as AuthenticatedDashboardRentalsRouteImport } from './routes/_authenticated/dashboard/rentals'
import { Route as AuthenticatedDashboardPromoRouteImport } from './routes/_authenticated/dashboard/promo'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardPaymentRouteImport } from './routes/_authenticated/dashboard/payment'
import { Route as AuthenticatedDashboardPasswordRouteImport } from './routes/_authenticated/dashboard/password'
import { Route as AuthenticatedDashboardNotificationsRouteImport } from './routes/_authenticated/dashboard/notifications'
import { Route as AuthenticatedDashboardMessagesRouteImport } from './routes/_authenticated/dashboard/messages'
import { Route as AuthenticatedDashboardListingsRouteImport } from './routes/_authenticated/dashboard/listings'
import { Route as AuthenticatedDashboardIdVerificationRouteImport } from './routes/_authenticated/dashboard/id-verification'
import { Route as AuthenticatedDashboardFinancialsRouteImport } from './routes/_authenticated/dashboard/financials'
import { Route as AuthenticatedDashboardBookingsRouteImport } from './routes/_authenticated/dashboard/bookings'
import { Route as AuthenticatedDashboardBookingRequestsRouteImport } from './routes/_authenticated/dashboard/booking-requests'
import { Route as AuthenticatedDashboardAvailabilityRouteImport } from './routes/_authenticated/dashboard/availability'
import { Route as AuthenticatedDashboardAddressesRouteImport } from './routes/_authenticated/dashboard/addresses'
import { Route as AuthenticatedCheckoutConfirmedRouteImport } from './routes/_authenticated/checkout/confirmed'
import { Route as AuthenticatedDashboardMessagesIndexRouteImport } from './routes/_authenticated/dashboard/messages.index'
import { Route as AuthenticatedDashboardMessagesConversation_idRouteImport } from './routes/_authenticated/dashboard/messages.$conversation_id'
import { Route as AuthenticatedDashboardListingsNewRouteImport } from './routes/_authenticated/dashboard/listings_.new'
import { Route as AuthenticatedDashboardBookingRequestsBookingIdRouteImport } from './routes/_authenticated/dashboard/booking-requests_.$bookingId'
import { Route as AuthenticatedDashboardRentalsBookingIdReturnRouteImport } from './routes/_authenticated/dashboard/rentals_.$bookingId.return'
import { Route as AuthenticatedDashboardListingsIdEditRouteImport } from './routes/_authenticated/dashboard/listings_.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingWithUsRoute = LendingWithUsRouteImport.update({
  id: '/lending-with-us',
  path: '/lending-with-us',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerServiceRoute = CustomerServiceRouteImport.update({
  id: '/customer-service',
  path: '/customer-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsIndexRoute = OccasionsIndexRouteImport.update({
  id: '/occasions/',
  path: '/occasions/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersIndexRoute = DesignersIndexRouteImport.update({
  id: '/designers/',
  path: '/designers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsSlugRoute = OccasionsSlugRouteImport.update({
  id: '/occasions/$slug',
  path: '/occasions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LendersLenderIdRoute = LendersLenderIdRouteImport.update({
  id: '/lenders/$lenderId',
  path: '/lenders/$lenderId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundsRoute = LegalRefundsRouteImport.update({
  id: '/legal/refunds',
  path: '/legal/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalLenderRoute = LegalLenderRouteImport.update({
  id: '/legal/lender',
  path: '/legal/lender',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDeliveryRoute = LegalDeliveryRouteImport.update({
  id: '/legal/delivery',
  path: '/legal/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const EditsSlugRoute = EditsSlugRouteImport.update({
  id: '/edits/$slug',
  path: '/edits/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DressesIdRoute = DressesIdRouteImport.update({
  id: '/dresses/$id',
  path: '/dresses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignersSlugRoute = DesignersSlugRouteImport.update({
  id: '/designers/$slug',
  path: '/designers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CitiesSlugRoute = CitiesSlugRouteImport.update({
  id: '/cities/$slug',
  path: '/cities/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedCheckoutIndexRoute =
  AuthenticatedCheckoutIndexRouteImport.update({
    id: '/checkout/',
    path: '/checkout/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardVacationRoute =
  AuthenticatedDashboardVacationRouteImport.update({
    id: '/vacation',
    path: '/vacation',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTwoHourDeliveryRoute =
  AuthenticatedDashboardTwoHourDeliveryRouteImport.update({
    id: '/two-hour-delivery',
    path: '/two-hour-delivery',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTryOnRoute =
  AuthenticatedDashboardTryOnRouteImport.update({
    id: '/try-on',
    path: '/try-on',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardShippingRoute =
  AuthenticatedDashboardShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardSavedRoute =
  AuthenticatedDashboardSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRentalsRoute =
  AuthenticatedDashboardRentalsRouteImport.update({
    id: '/rentals',
    path: '/rentals',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPromoRoute =
  AuthenticatedDashboardPromoRouteImport.update({
    id: '/promo',
    path: '/promo',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPaymentRoute =
  AuthenticatedDashboardPaymentRouteImport.update({
    id: '/payment',
    path: '/payment',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardPasswordRoute =
  AuthenticatedDashboardPasswordRouteImport.update({
    id: '/password',
    path: '/password',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardNotificationsRoute =
  AuthenticatedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardMessagesRoute =
  AuthenticatedDashboardMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardListingsRoute =
  AuthenticatedDashboardListingsRouteImport.update({
    id: '/listings',
    path: '/listings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardIdVerificationRoute =
  AuthenticatedDashboardIdVerificationRouteImport.update({
    id: '/id-verification',
    path: '/id-verification',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardFinancialsRoute =
  AuthenticatedDashboardFinancialsRouteImport.update({
    id: '/financials',
    path: '/financials',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingsRoute =
  AuthenticatedDashboardBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingRequestsRoute =
  AuthenticatedDashboardBookingRequestsRouteImport.update({
    id: '/booking-requests',
    path: '/booking-requests',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAvailabilityRoute =
  AuthenticatedDashboardAvailabilityRouteImport.update({
    id: '/availability',
    path: '/availability',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAddressesRoute =
  AuthenticatedDashboardAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedCheckoutConfirmedRoute =
  AuthenticatedCheckoutConfirmedRouteImport.update({
    id: '/checkout/confirmed',
    path: '/checkout/confirmed',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardMessagesIndexRoute =
  AuthenticatedDashboardMessagesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardMessagesRoute,
  } as any)
const AuthenticatedDashboardMessagesConversation_idRoute =
  AuthenticatedDashboardMessagesConversation_idRouteImport.update({
    id: '/$conversation_id',
    path: '/$conversation_id',
    getParentRoute: () => AuthenticatedDashboardMessagesRoute,
  } as any)
const AuthenticatedDashboardListingsNewRoute =
  AuthenticatedDashboardListingsNewRouteImport.update({
    id: '/listings_/new',
    path: '/listings/new',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBookingRequestsBookingIdRoute =
  AuthenticatedDashboardBookingRequestsBookingIdRouteImport.update({
    id: '/booking-requests_/$bookingId',
    path: '/booking-requests/$bookingId',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRentalsBookingIdReturnRoute =
  AuthenticatedDashboardRentalsBookingIdReturnRouteImport.update({
    id: '/rentals_/$bookingId/return',
    path: '/rentals/$bookingId/return',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardListingsIdEditRoute =
  AuthenticatedDashboardListingsIdEditRouteImport.update({
    id: '/listings_/$id/edit',
    path: '/listings/$id/edit',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/customer-service': typeof CustomerServiceRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lending-with-us': typeof LendingWithUsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/designers/$slug': typeof DesignersSlugRoute
  '/dresses/$id': typeof DressesIdRoute
  '/edits/$slug': typeof EditsSlugRoute
  '/legal/delivery': typeof LegalDeliveryRoute
  '/legal/lender': typeof LegalLenderRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lenders/$lenderId': typeof LendersLenderIdRoute
  '/occasions/$slug': typeof OccasionsSlugRoute
  '/designers/': typeof DesignersIndexRoute
  '/occasions/': typeof OccasionsIndexRoute
  '/checkout/confirmed': typeof AuthenticatedCheckoutConfirmedRoute
  '/dashboard/addresses': typeof AuthenticatedDashboardAddressesRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/booking-requests': typeof AuthenticatedDashboardBookingRequestsRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/financials': typeof AuthenticatedDashboardFinancialsRoute
  '/dashboard/id-verification': typeof AuthenticatedDashboardIdVerificationRoute
  '/dashboard/listings': typeof AuthenticatedDashboardListingsRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesRouteWithChildren
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/password': typeof AuthenticatedDashboardPasswordRoute
  '/dashboard/payment': typeof AuthenticatedDashboardPaymentRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/promo': typeof AuthenticatedDashboardPromoRoute
  '/dashboard/rentals': typeof AuthenticatedDashboardRentalsRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/shipping': typeof AuthenticatedDashboardShippingRoute
  '/dashboard/try-on': typeof AuthenticatedDashboardTryOnRoute
  '/dashboard/two-hour-delivery': typeof AuthenticatedDashboardTwoHourDeliveryRoute
  '/dashboard/vacation': typeof AuthenticatedDashboardVacationRoute
  '/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/booking-requests/$bookingId': typeof AuthenticatedDashboardBookingRequestsBookingIdRoute
  '/dashboard/listings/new': typeof AuthenticatedDashboardListingsNewRoute
  '/dashboard/messages/$conversation_id': typeof AuthenticatedDashboardMessagesConversation_idRoute
  '/dashboard/messages/': typeof AuthenticatedDashboardMessagesIndexRoute
  '/dashboard/listings/$id/edit': typeof AuthenticatedDashboardListingsIdEditRoute
  '/dashboard/rentals/$bookingId/return': typeof AuthenticatedDashboardRentalsBookingIdReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/customer-service': typeof CustomerServiceRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lending-with-us': typeof LendingWithUsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/designers/$slug': typeof DesignersSlugRoute
  '/dresses/$id': typeof DressesIdRoute
  '/edits/$slug': typeof EditsSlugRoute
  '/legal/delivery': typeof LegalDeliveryRoute
  '/legal/lender': typeof LegalLenderRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lenders/$lenderId': typeof LendersLenderIdRoute
  '/occasions/$slug': typeof OccasionsSlugRoute
  '/designers': typeof DesignersIndexRoute
  '/occasions': typeof OccasionsIndexRoute
  '/checkout/confirmed': typeof AuthenticatedCheckoutConfirmedRoute
  '/dashboard/addresses': typeof AuthenticatedDashboardAddressesRoute
  '/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/dashboard/booking-requests': typeof AuthenticatedDashboardBookingRequestsRoute
  '/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/dashboard/financials': typeof AuthenticatedDashboardFinancialsRoute
  '/dashboard/id-verification': typeof AuthenticatedDashboardIdVerificationRoute
  '/dashboard/listings': typeof AuthenticatedDashboardListingsRoute
  '/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/dashboard/password': typeof AuthenticatedDashboardPasswordRoute
  '/dashboard/payment': typeof AuthenticatedDashboardPaymentRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/promo': typeof AuthenticatedDashboardPromoRoute
  '/dashboard/rentals': typeof AuthenticatedDashboardRentalsRoute
  '/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/dashboard/shipping': typeof AuthenticatedDashboardShippingRoute
  '/dashboard/try-on': typeof AuthenticatedDashboardTryOnRoute
  '/dashboard/two-hour-delivery': typeof AuthenticatedDashboardTwoHourDeliveryRoute
  '/dashboard/vacation': typeof AuthenticatedDashboardVacationRoute
  '/checkout': typeof AuthenticatedCheckoutIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/booking-requests/$bookingId': typeof AuthenticatedDashboardBookingRequestsBookingIdRoute
  '/dashboard/listings/new': typeof AuthenticatedDashboardListingsNewRoute
  '/dashboard/messages/$conversation_id': typeof AuthenticatedDashboardMessagesConversation_idRoute
  '/dashboard/messages': typeof AuthenticatedDashboardMessagesIndexRoute
  '/dashboard/listings/$id/edit': typeof AuthenticatedDashboardListingsIdEditRoute
  '/dashboard/rentals/$bookingId/return': typeof AuthenticatedDashboardRentalsBookingIdReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/browse': typeof BrowseRoute
  '/contact': typeof ContactRoute
  '/customer-service': typeof CustomerServiceRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/lending-with-us': typeof LendingWithUsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/cities/$slug': typeof CitiesSlugRoute
  '/designers/$slug': typeof DesignersSlugRoute
  '/dresses/$id': typeof DressesIdRoute
  '/edits/$slug': typeof EditsSlugRoute
  '/legal/delivery': typeof LegalDeliveryRoute
  '/legal/lender': typeof LegalLenderRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refunds': typeof LegalRefundsRoute
  '/legal/terms': typeof LegalTermsRoute
  '/lenders/$lenderId': typeof LendersLenderIdRoute
  '/occasions/$slug': typeof OccasionsSlugRoute
  '/designers/': typeof DesignersIndexRoute
  '/occasions/': typeof OccasionsIndexRoute
  '/_authenticated/checkout/confirmed': typeof AuthenticatedCheckoutConfirmedRoute
  '/_authenticated/dashboard/addresses': typeof AuthenticatedDashboardAddressesRoute
  '/_authenticated/dashboard/availability': typeof AuthenticatedDashboardAvailabilityRoute
  '/_authenticated/dashboard/booking-requests': typeof AuthenticatedDashboardBookingRequestsRoute
  '/_authenticated/dashboard/bookings': typeof AuthenticatedDashboardBookingsRoute
  '/_authenticated/dashboard/financials': typeof AuthenticatedDashboardFinancialsRoute
  '/_authenticated/dashboard/id-verification': typeof AuthenticatedDashboardIdVerificationRoute
  '/_authenticated/dashboard/listings': typeof AuthenticatedDashboardListingsRoute
  '/_authenticated/dashboard/messages': typeof AuthenticatedDashboardMessagesRouteWithChildren
  '/_authenticated/dashboard/notifications': typeof AuthenticatedDashboardNotificationsRoute
  '/_authenticated/dashboard/password': typeof AuthenticatedDashboardPasswordRoute
  '/_authenticated/dashboard/payment': typeof AuthenticatedDashboardPaymentRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/promo': typeof AuthenticatedDashboardPromoRoute
  '/_authenticated/dashboard/rentals': typeof AuthenticatedDashboardRentalsRoute
  '/_authenticated/dashboard/saved': typeof AuthenticatedDashboardSavedRoute
  '/_authenticated/dashboard/shipping': typeof AuthenticatedDashboardShippingRoute
  '/_authenticated/dashboard/try-on': typeof AuthenticatedDashboardTryOnRoute
  '/_authenticated/dashboard/two-hour-delivery': typeof AuthenticatedDashboardTwoHourDeliveryRoute
  '/_authenticated/dashboard/vacation': typeof AuthenticatedDashboardVacationRoute
  '/_authenticated/checkout/': typeof AuthenticatedCheckoutIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/booking-requests_/$bookingId': typeof AuthenticatedDashboardBookingRequestsBookingIdRoute
  '/_authenticated/dashboard/listings_/new': typeof AuthenticatedDashboardListingsNewRoute
  '/_authenticated/dashboard/messages/$conversation_id': typeof AuthenticatedDashboardMessagesConversation_idRoute
  '/_authenticated/dashboard/messages/': typeof AuthenticatedDashboardMessagesIndexRoute
  '/_authenticated/dashboard/listings_/$id/edit': typeof AuthenticatedDashboardListingsIdEditRoute
  '/_authenticated/dashboard/rentals_/$bookingId/return': typeof AuthenticatedDashboardRentalsBookingIdReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/contact'
    | '/customer-service'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/lending-with-us'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/notifications'
    | '/saved'
    | '/cities/$slug'
    | '/designers/$slug'
    | '/dresses/$id'
    | '/edits/$slug'
    | '/legal/delivery'
    | '/legal/lender'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/lenders/$lenderId'
    | '/occasions/$slug'
    | '/designers/'
    | '/occasions/'
    | '/checkout/confirmed'
    | '/dashboard/addresses'
    | '/dashboard/availability'
    | '/dashboard/booking-requests'
    | '/dashboard/bookings'
    | '/dashboard/financials'
    | '/dashboard/id-verification'
    | '/dashboard/listings'
    | '/dashboard/messages'
    | '/dashboard/notifications'
    | '/dashboard/password'
    | '/dashboard/payment'
    | '/dashboard/profile'
    | '/dashboard/promo'
    | '/dashboard/rentals'
    | '/dashboard/saved'
    | '/dashboard/shipping'
    | '/dashboard/try-on'
    | '/dashboard/two-hour-delivery'
    | '/dashboard/vacation'
    | '/checkout/'
    | '/dashboard/'
    | '/dashboard/booking-requests/$bookingId'
    | '/dashboard/listings/new'
    | '/dashboard/messages/$conversation_id'
    | '/dashboard/messages/'
    | '/dashboard/listings/$id/edit'
    | '/dashboard/rentals/$bookingId/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/contact'
    | '/customer-service'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/lending-with-us'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/notifications'
    | '/saved'
    | '/cities/$slug'
    | '/designers/$slug'
    | '/dresses/$id'
    | '/edits/$slug'
    | '/legal/delivery'
    | '/legal/lender'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/lenders/$lenderId'
    | '/occasions/$slug'
    | '/designers'
    | '/occasions'
    | '/checkout/confirmed'
    | '/dashboard/addresses'
    | '/dashboard/availability'
    | '/dashboard/booking-requests'
    | '/dashboard/bookings'
    | '/dashboard/financials'
    | '/dashboard/id-verification'
    | '/dashboard/listings'
    | '/dashboard/notifications'
    | '/dashboard/password'
    | '/dashboard/payment'
    | '/dashboard/profile'
    | '/dashboard/promo'
    | '/dashboard/rentals'
    | '/dashboard/saved'
    | '/dashboard/shipping'
    | '/dashboard/try-on'
    | '/dashboard/two-hour-delivery'
    | '/dashboard/vacation'
    | '/checkout'
    | '/dashboard'
    | '/dashboard/booking-requests/$bookingId'
    | '/dashboard/listings/new'
    | '/dashboard/messages/$conversation_id'
    | '/dashboard/messages'
    | '/dashboard/listings/$id/edit'
    | '/dashboard/rentals/$bookingId/return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/browse'
    | '/contact'
    | '/customer-service'
    | '/faq'
    | '/forgot-password'
    | '/how-it-works'
    | '/lending-with-us'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/saved'
    | '/cities/$slug'
    | '/designers/$slug'
    | '/dresses/$id'
    | '/edits/$slug'
    | '/legal/delivery'
    | '/legal/lender'
    | '/legal/privacy'
    | '/legal/refunds'
    | '/legal/terms'
    | '/lenders/$lenderId'
    | '/occasions/$slug'
    | '/designers/'
    | '/occasions/'
    | '/_authenticated/checkout/confirmed'
    | '/_authenticated/dashboard/addresses'
    | '/_authenticated/dashboard/availability'
    | '/_authenticated/dashboard/booking-requests'
    | '/_authenticated/dashboard/bookings'
    | '/_authenticated/dashboard/financials'
    | '/_authenticated/dashboard/id-verification'
    | '/_authenticated/dashboard/listings'
    | '/_authenticated/dashboard/messages'
    | '/_authenticated/dashboard/notifications'
    | '/_authenticated/dashboard/password'
    | '/_authenticated/dashboard/payment'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/promo'
    | '/_authenticated/dashboard/rentals'
    | '/_authenticated/dashboard/saved'
    | '/_authenticated/dashboard/shipping'
    | '/_authenticated/dashboard/try-on'
    | '/_authenticated/dashboard/two-hour-delivery'
    | '/_authenticated/dashboard/vacation'
    | '/_authenticated/checkout/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/booking-requests_/$bookingId'
    | '/_authenticated/dashboard/listings_/new'
    | '/_authenticated/dashboard/messages/$conversation_id'
    | '/_authenticated/dashboard/messages/'
    | '/_authenticated/dashboard/listings_/$id/edit'
    | '/_authenticated/dashboard/rentals_/$bookingId/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BrowseRoute: typeof BrowseRoute
  ContactRoute: typeof ContactRoute
  CustomerServiceRoute: typeof CustomerServiceRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LendingWithUsRoute: typeof LendingWithUsRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  CitiesSlugRoute: typeof CitiesSlugRoute
  DesignersSlugRoute: typeof DesignersSlugRoute
  DressesIdRoute: typeof DressesIdRoute
  EditsSlugRoute: typeof EditsSlugRoute
  LegalDeliveryRoute: typeof LegalDeliveryRoute
  LegalLenderRoute: typeof LegalLenderRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundsRoute: typeof LegalRefundsRoute
  LegalTermsRoute: typeof LegalTermsRoute
  LendersLenderIdRoute: typeof LendersLenderIdRoute
  OccasionsSlugRoute: typeof OccasionsSlugRoute
  DesignersIndexRoute: typeof DesignersIndexRoute
  OccasionsIndexRoute: typeof OccasionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending-with-us': {
      id: '/lending-with-us'
      path: '/lending-with-us'
      fullPath: '/lending-with-us'
      preLoaderRoute: typeof LendingWithUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-service': {
      id: '/customer-service'
      path: '/customer-service'
      fullPath: '/customer-service'
      preLoaderRoute: typeof CustomerServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/': {
      id: '/occasions/'
      path: '/occasions'
      fullPath: '/occasions/'
      preLoaderRoute: typeof OccasionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers/': {
      id: '/designers/'
      path: '/designers'
      fullPath: '/designers/'
      preLoaderRoute: typeof DesignersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions/$slug': {
      id: '/occasions/$slug'
      path: '/occasions/$slug'
      fullPath: '/occasions/$slug'
      preLoaderRoute: typeof OccasionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenders/$lenderId': {
      id: '/lenders/$lenderId'
      path: '/lenders/$lenderId'
      fullPath: '/lenders/$lenderId'
      preLoaderRoute: typeof LendersLenderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refunds': {
      id: '/legal/refunds'
      path: '/legal/refunds'
      fullPath: '/legal/refunds'
      preLoaderRoute: typeof LegalRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/lender': {
      id: '/legal/lender'
      path: '/legal/lender'
      fullPath: '/legal/lender'
      preLoaderRoute: typeof LegalLenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/delivery': {
      id: '/legal/delivery'
      path: '/legal/delivery'
      fullPath: '/legal/delivery'
      preLoaderRoute: typeof LegalDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edits/$slug': {
      id: '/edits/$slug'
      path: '/edits/$slug'
      fullPath: '/edits/$slug'
      preLoaderRoute: typeof EditsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dresses/$id': {
      id: '/dresses/$id'
      path: '/dresses/$id'
      fullPath: '/dresses/$id'
      preLoaderRoute: typeof DressesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designers/$slug': {
      id: '/designers/$slug'
      path: '/designers/$slug'
      fullPath: '/designers/$slug'
      preLoaderRoute: typeof DesignersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cities/$slug': {
      id: '/cities/$slug'
      path: '/cities/$slug'
      fullPath: '/cities/$slug'
      preLoaderRoute: typeof CitiesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/checkout/': {
      id: '/_authenticated/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AuthenticatedCheckoutIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/vacation': {
      id: '/_authenticated/dashboard/vacation'
      path: '/vacation'
      fullPath: '/dashboard/vacation'
      preLoaderRoute: typeof AuthenticatedDashboardVacationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/two-hour-delivery': {
      id: '/_authenticated/dashboard/two-hour-delivery'
      path: '/two-hour-delivery'
      fullPath: '/dashboard/two-hour-delivery'
      preLoaderRoute: typeof AuthenticatedDashboardTwoHourDeliveryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/try-on': {
      id: '/_authenticated/dashboard/try-on'
      path: '/try-on'
      fullPath: '/dashboard/try-on'
      preLoaderRoute: typeof AuthenticatedDashboardTryOnRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/shipping': {
      id: '/_authenticated/dashboard/shipping'
      path: '/shipping'
      fullPath: '/dashboard/shipping'
      preLoaderRoute: typeof AuthenticatedDashboardShippingRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/saved': {
      id: '/_authenticated/dashboard/saved'
      path: '/saved'
      fullPath: '/dashboard/saved'
      preLoaderRoute: typeof AuthenticatedDashboardSavedRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rentals': {
      id: '/_authenticated/dashboard/rentals'
      path: '/rentals'
      fullPath: '/dashboard/rentals'
      preLoaderRoute: typeof AuthenticatedDashboardRentalsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/promo': {
      id: '/_authenticated/dashboard/promo'
      path: '/promo'
      fullPath: '/dashboard/promo'
      preLoaderRoute: typeof AuthenticatedDashboardPromoRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/payment': {
      id: '/_authenticated/dashboard/payment'
      path: '/payment'
      fullPath: '/dashboard/payment'
      preLoaderRoute: typeof AuthenticatedDashboardPaymentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/password': {
      id: '/_authenticated/dashboard/password'
      path: '/password'
      fullPath: '/dashboard/password'
      preLoaderRoute: typeof AuthenticatedDashboardPasswordRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/notifications': {
      id: '/_authenticated/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof AuthenticatedDashboardNotificationsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/messages': {
      id: '/_authenticated/dashboard/messages'
      path: '/messages'
      fullPath: '/dashboard/messages'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/listings': {
      id: '/_authenticated/dashboard/listings'
      path: '/listings'
      fullPath: '/dashboard/listings'
      preLoaderRoute: typeof AuthenticatedDashboardListingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/id-verification': {
      id: '/_authenticated/dashboard/id-verification'
      path: '/id-verification'
      fullPath: '/dashboard/id-verification'
      preLoaderRoute: typeof AuthenticatedDashboardIdVerificationRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/financials': {
      id: '/_authenticated/dashboard/financials'
      path: '/financials'
      fullPath: '/dashboard/financials'
      preLoaderRoute: typeof AuthenticatedDashboardFinancialsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bookings': {
      id: '/_authenticated/dashboard/bookings'
      path: '/bookings'
      fullPath: '/dashboard/bookings'
      preLoaderRoute: typeof AuthenticatedDashboardBookingsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/booking-requests': {
      id: '/_authenticated/dashboard/booking-requests'
      path: '/booking-requests'
      fullPath: '/dashboard/booking-requests'
      preLoaderRoute: typeof AuthenticatedDashboardBookingRequestsRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/availability': {
      id: '/_authenticated/dashboard/availability'
      path: '/availability'
      fullPath: '/dashboard/availability'
      preLoaderRoute: typeof AuthenticatedDashboardAvailabilityRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/addresses': {
      id: '/_authenticated/dashboard/addresses'
      path: '/addresses'
      fullPath: '/dashboard/addresses'
      preLoaderRoute: typeof AuthenticatedDashboardAddressesRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/checkout/confirmed': {
      id: '/_authenticated/checkout/confirmed'
      path: '/checkout/confirmed'
      fullPath: '/checkout/confirmed'
      preLoaderRoute: typeof AuthenticatedCheckoutConfirmedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/messages/': {
      id: '/_authenticated/dashboard/messages/'
      path: '/'
      fullPath: '/dashboard/messages/'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardMessagesRoute
    }
    '/_authenticated/dashboard/messages/$conversation_id': {
      id: '/_authenticated/dashboard/messages/$conversation_id'
      path: '/$conversation_id'
      fullPath: '/dashboard/messages/$conversation_id'
      preLoaderRoute: typeof AuthenticatedDashboardMessagesConversation_idRouteImport
      parentRoute: typeof AuthenticatedDashboardMessagesRoute
    }
    '/_authenticated/dashboard/listings_/new': {
      id: '/_authenticated/dashboard/listings_/new'
      path: '/listings/new'
      fullPath: '/dashboard/listings/new'
      preLoaderRoute: typeof AuthenticatedDashboardListingsNewRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/booking-requests_/$bookingId': {
      id: '/_authenticated/dashboard/booking-requests_/$bookingId'
      path: '/booking-requests/$bookingId'
      fullPath: '/dashboard/booking-requests/$bookingId'
      preLoaderRoute: typeof AuthenticatedDashboardBookingRequestsBookingIdRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rentals_/$bookingId/return': {
      id: '/_authenticated/dashboard/rentals_/$bookingId/return'
      path: '/rentals/$bookingId/return'
      fullPath: '/dashboard/rentals/$bookingId/return'
      preLoaderRoute: typeof AuthenticatedDashboardRentalsBookingIdReturnRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/listings_/$id/edit': {
      id: '/_authenticated/dashboard/listings_/$id/edit'
      path: '/listings/$id/edit'
      fullPath: '/dashboard/listings/$id/edit'
      preLoaderRoute: typeof AuthenticatedDashboardListingsIdEditRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardMessagesRouteChildren {
  AuthenticatedDashboardMessagesConversation_idRoute: typeof AuthenticatedDashboardMessagesConversation_idRoute
  AuthenticatedDashboardMessagesIndexRoute: typeof AuthenticatedDashboardMessagesIndexRoute
}

const AuthenticatedDashboardMessagesRouteChildren: AuthenticatedDashboardMessagesRouteChildren =
  {
    AuthenticatedDashboardMessagesConversation_idRoute:
      AuthenticatedDashboardMessagesConversation_idRoute,
    AuthenticatedDashboardMessagesIndexRoute:
      AuthenticatedDashboardMessagesIndexRoute,
  }

const AuthenticatedDashboardMessagesRouteWithChildren =
  AuthenticatedDashboardMessagesRoute._addFileChildren(
    AuthenticatedDashboardMessagesRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAddressesRoute: typeof AuthenticatedDashboardAddressesRoute
  AuthenticatedDashboardAvailabilityRoute: typeof AuthenticatedDashboardAvailabilityRoute
  AuthenticatedDashboardBookingRequestsRoute: typeof AuthenticatedDashboardBookingRequestsRoute
  AuthenticatedDashboardBookingsRoute: typeof AuthenticatedDashboardBookingsRoute
  AuthenticatedDashboardFinancialsRoute: typeof AuthenticatedDashboardFinancialsRoute
  AuthenticatedDashboardIdVerificationRoute: typeof AuthenticatedDashboardIdVerificationRoute
  AuthenticatedDashboardListingsRoute: typeof AuthenticatedDashboardListingsRoute
  AuthenticatedDashboardMessagesRoute: typeof AuthenticatedDashboardMessagesRouteWithChildren
  AuthenticatedDashboardNotificationsRoute: typeof AuthenticatedDashboardNotificationsRoute
  AuthenticatedDashboardPasswordRoute: typeof AuthenticatedDashboardPasswordRoute
  AuthenticatedDashboardPaymentRoute: typeof AuthenticatedDashboardPaymentRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardPromoRoute: typeof AuthenticatedDashboardPromoRoute
  AuthenticatedDashboardRentalsRoute: typeof AuthenticatedDashboardRentalsRoute
  AuthenticatedDashboardSavedRoute: typeof AuthenticatedDashboardSavedRoute
  AuthenticatedDashboardShippingRoute: typeof AuthenticatedDashboardShippingRoute
  AuthenticatedDashboardTryOnRoute: typeof AuthenticatedDashboardTryOnRoute
  AuthenticatedDashboardTwoHourDeliveryRoute: typeof AuthenticatedDashboardTwoHourDeliveryRoute
  AuthenticatedDashboardVacationRoute: typeof AuthenticatedDashboardVacationRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardBookingRequestsBookingIdRoute: typeof AuthenticatedDashboardBookingRequestsBookingIdRoute
  AuthenticatedDashboardListingsNewRoute: typeof AuthenticatedDashboardListingsNewRoute
  AuthenticatedDashboardListingsIdEditRoute: typeof AuthenticatedDashboardListingsIdEditRoute
  AuthenticatedDashboardRentalsBookingIdReturnRoute: typeof AuthenticatedDashboardRentalsBookingIdReturnRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAddressesRoute: AuthenticatedDashboardAddressesRoute,
    AuthenticatedDashboardAvailabilityRoute:
      AuthenticatedDashboardAvailabilityRoute,
    AuthenticatedDashboardBookingRequestsRoute:
      AuthenticatedDashboardBookingRequestsRoute,
    AuthenticatedDashboardBookingsRoute: AuthenticatedDashboardBookingsRoute,
    AuthenticatedDashboardFinancialsRoute:
      AuthenticatedDashboardFinancialsRoute,
    AuthenticatedDashboardIdVerificationRoute:
      AuthenticatedDashboardIdVerificationRoute,
    AuthenticatedDashboardListingsRoute: AuthenticatedDashboardListingsRoute,
    AuthenticatedDashboardMessagesRoute:
      AuthenticatedDashboardMessagesRouteWithChildren,
    AuthenticatedDashboardNotificationsRoute:
      AuthenticatedDashboardNotificationsRoute,
    AuthenticatedDashboardPasswordRoute: AuthenticatedDashboardPasswordRoute,
    AuthenticatedDashboardPaymentRoute: AuthenticatedDashboardPaymentRoute,
    AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
    AuthenticatedDashboardPromoRoute: AuthenticatedDashboardPromoRoute,
    AuthenticatedDashboardRentalsRoute: AuthenticatedDashboardRentalsRoute,
    AuthenticatedDashboardSavedRoute: AuthenticatedDashboardSavedRoute,
    AuthenticatedDashboardShippingRoute: AuthenticatedDashboardShippingRoute,
    AuthenticatedDashboardTryOnRoute: AuthenticatedDashboardTryOnRoute,
    AuthenticatedDashboardTwoHourDeliveryRoute:
      AuthenticatedDashboardTwoHourDeliveryRoute,
    AuthenticatedDashboardVacationRoute: AuthenticatedDashboardVacationRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
    AuthenticatedDashboardBookingRequestsBookingIdRoute:
      AuthenticatedDashboardBookingRequestsBookingIdRoute,
    AuthenticatedDashboardListingsNewRoute:
      AuthenticatedDashboardListingsNewRoute,
    AuthenticatedDashboardListingsIdEditRoute:
      AuthenticatedDashboardListingsIdEditRoute,
    AuthenticatedDashboardRentalsBookingIdReturnRoute:
      AuthenticatedDashboardRentalsBookingIdReturnRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedCheckoutConfirmedRoute: typeof AuthenticatedCheckoutConfirmedRoute
  AuthenticatedCheckoutIndexRoute: typeof AuthenticatedCheckoutIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedCheckoutConfirmedRoute: AuthenticatedCheckoutConfirmedRoute,
  AuthenticatedCheckoutIndexRoute: AuthenticatedCheckoutIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BrowseRoute: BrowseRoute,
  ContactRoute: ContactRoute,
  CustomerServiceRoute: CustomerServiceRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LendingWithUsRoute: LendingWithUsRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  CitiesSlugRoute: CitiesSlugRoute,
  DesignersSlugRoute: DesignersSlugRoute,
  DressesIdRoute: DressesIdRoute,
  EditsSlugRoute: EditsSlugRoute,
  LegalDeliveryRoute: LegalDeliveryRoute,
  LegalLenderRoute: LegalLenderRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundsRoute: LegalRefundsRoute,
  LegalTermsRoute: LegalTermsRoute,
  LendersLenderIdRoute: LendersLenderIdRoute,
  OccasionsSlugRoute: OccasionsSlugRoute,
  DesignersIndexRoute: DesignersIndexRoute,
  OccasionsIndexRoute: OccasionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
